require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.keymaps_plug"
require "user.colorscheme"
require "user.comment"
require "user.autopairs"
require "user.bufferline"
require "user.cmp"
require "user.lsp"
require "user.telescope"
-- require "user.treesitter"
-- require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
-- require "user.toggleterm"
-- require "user.project"
-- require "user.impatient"
-- require "user.indentline"
-- require "user.alpha"
-- require "user.whichkey"
-- require "user.autocommands"
